AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for MeteoPipe app auth flow using cognito

Globals:
  Function:
    Timeout: 3
    Runtime: python3.8

Parameters: #section for defining variables which i will referred later on inside this template
  AppName:
    Type: String
    Default: MeteoPipe

Resources:
  PostRegistrationUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: postregistration/
      Handler: register_user.lambda_handler
      Layers:
        - Fn::ImportValue:
            !Sub "${AppName}-LibLambdaLayer" #need to use layer versioning enforce by AWS
      Role:
        Fn::ImportValue: !Sub "${AppName}-CognitoPostAuthRole"
      Environment:
        Variables:
          REGION: eu-central-1
          TABLE_NAME: MeteoPipeUsers
#    DependsOn:
#      - arn:aws:iam::045341403599:role/MeteoPipeLambdaRoleForPostAuthorization
#      - arn:aws:lambda:eu-central-1:045341403599:layer:LibLayer:7
