AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LambdaFunction

  Sample SAM Template for LambdaFunction

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.8

Resources:
  RegisterDeviceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: meteo_pipe/register_device/
      Handler: register_device.lambda_handler
      Layers:
        - !Ref LibLayer
      Role: !Ref MeteoPipeAWSIoTRole
      Events:
        RegiserDeviceAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /register_device
            Method: post
    DependsOn:
      - !Ref MeteoPipeAWSIoTRole
      - !Ref LibLayer
